### ISSUE TITLE
Improve mobile responsiveness  of website 

### ISSUE THREAD

**Issue by maxxcrawford** [codefortulsa/courtbot-python#35]
Issues: 

- [x] Hero section has a min-width of 420px (Should be 320px) 
- [ ] Hamburger menu not functioning 
- [x] Poor padding/spacing of sponsor logos

**Comment by jeremiahbrem** [comment]
Hi there,
I fixed the hamburger drop-down and I'd like to make a pull request.

**Comment by syk1112** [comment]
@jeremiahbrem thanks for fixing this issue!
