### ISSUE TITLE
Hard coded year when setting up reminder

### ISSUE THREAD

**Issue by syk1102** [codefortulsa/courtbot-python#44]
When setting up reminder for a specific case, the year is hard coded to `2018` instead of getting it from the case number/id
https://github.com/codefortulsa/courtbot-python/blob/master/sms/views.py#L29

**Comment by kendallcorner** [comment]
It appears to be more than that. It needs to split out the type, year, and number from the 'case number' received in the text message. @Yahyaal is working on this.

Output of how the code is currently written run through the interpreter.
![Screenshot from 2019-10-27 12-45-51](https://user-images.githubusercontent.com/3195251/67638905-d8b5af80-f8b7-11e9-8208-653ccd4f90fc.png)

**Comment by syk1102** [comment]
Issue close because `courtbot-python` no longer uses `sms`
