### ISSUE TITLE
Create a form for text reminder

### ISSUE THREAD

**Issue by syk1112** [codefortulsa/courtbot-python#61]
# About this Issue
We would like to have forms be available so that we can help non-profit or individuals add a text reminder for court dates coming up.

# Acceptance Criteria
- [ ] Following fields should be available:
  - Case number(s)
  - Phone number (for reminder)
  - Phone number (for other people who wants to be reminded too)

**Comment by jeremiahbrem** [comment]
Been working on a possible form solution
