### ISSUE TITLE
"2. What if I still can't find my case number?" Link Broken

### ISSUE THREAD

**Issue by schisa** [codefortulsa/courtbot-python#79]
**Repro steps:** 
1. Navigate to http://court.bot
2. Scroll down to the FAQ question "2. What if I still can't find my case number?"
3. Click the link: www.oscn.net/dockets/search.aspx

==Expected==
I am taken to www.oscn.net/dockets/search.aspx

==Actual==
I am taken to http://court.bot/“www.oscn.net/dockets/search.aspx” and get a 404.

**Comment by schisa** [comment]
My apologies if this is not the place for this type of issue.

**Comment by syk1112** [comment]
👋 Hi! Thank you for filing an issue. This is the best to place to file it! I tested and can confirm that this is happening. I'll put this on a list of bugs people can work on.

**Comment by Serhazor** [comment]
Trying to check what the issue is and code seems to be okay. I did not use django before but would it be correct to assume that it would have to be a new path or httpredirect? 

Thanks

**Comment by jwhitlock** [comment]
I believe the issue is in the content template, which is mostly HTML:

https://github.com/codefortulsa/courtbot-python/blob/bb3393c8b82a65d1533d13e893fcc3f081066be4/website/templates/index.html#L113-L115

That should be ``<a href=“https://www.oscn.net/dockets/search.aspx”>``. Without the ``https://``, it treats it as a relative URL.

**Comment by Serhazor** [comment]
Created a pull request, please check. 
Thanks.

**Comment by Serhazor** [comment]
> I believe the issue is in the content template, which is mostly HTML:
> 
> https://github.com/codefortulsa/courtbot-python/blob/bb3393c8b82a65d1533d13e893fcc3f081066be4/website/templates/index.html#L111-L116
> 
> That should be `<a href=“https://www.oscn.net/dockets/search.aspx”>`. Without the `https://`, it treats it as a relative URL.
> 
> The formatting could use a little love as well - line up the `<div>`, make the spacing consistent with other FAQ entries, etc.

you were right.... I've tested with "http://" instead of "https://" before and it did not work, but now it works. Will create another PR.
