### ISSUE TITLE
Register .bot domain from Amazon

### ISSUE THREAD

**Issue by maxxcrawford** [codefortulsa/courtbot-python#8]
URL: https://www.amazonregistry.com/bot/validation

## .bot domain registration steps: 
1. Find your .BOT domain
2. Sign into your Amazon account
3. Validate your published bot
4. Select registrar and additional services
5. Complete registration and setup

## Validate your published bot: 

<img width="322" alt="image" src="https://user-images.githubusercontent.com/2692333/61173499-e0945280-a559-11e9-928e-8ac75747430a.png">

Validation is the process of proving you have access rights to the bot you are using to meet validation requirements. This allows us to keep the .BOT Top Level Domain for bots and retain the domain as a community. Validation associates your bot to a specific validation token if successful. The token is then used to register a .BOT domain name.

To ensure only eligible customers register a .BOT domain name, we need you to validate your bot. Validation tokens are issued to customers who pass validation. The validation token is required to register your .BOT domain name.

**Comment by kendallcorner** [comment]
Done! Should point to the Heroku in 6-48 hours

**Comment by maxxcrawford** [comment]
🙌 🙌 🙌
