### ISSUE TITLE
Google Chrome Security Warning on Court.Bot

### ISSUE THREAD

**Issue by schisa** [codefortulsa/courtbot-python#82]
**Repro Steps:**
_Note_I was using Google Chrome. 

1. Go to google.com
2. Google "Tulsa court bot"
3. Click the first result

==Expected==
Safely arrive at court.bot

==Actual==
See a 
"Your connection is not private
Attackers might be trying to steal your information from court.bot (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_DATE_INVALID" warning. 
![Screen Shot 2020-08-31 at 10 00 06 PM](https://user-images.githubusercontent.com/3689693/91786365-79aa8080-ebd5-11ea-8abf-badc144744c9.png)

**Comment by groovecoder** [comment]
Thanks for filing! Fixed by enabling heroku:certs:auto.
